Object.assign(exports, {
    ROAD_DATA: "roadData",
    BUILD_DATA: "buildData",
    PHASE_ROADS: 0,
    PHASE_EXTENSIONS: 1,
    EXTENSION_OPTIONS: "eo",
    TOWER_BUILD_STEP: 1001,
    TOWER_BOTTLENECK_NORTH_STEP: 1002,
    TOWER_BOTTLENECK_EAST_STEP: 1102,
    TOWER_BOTTLENECK_SOUTH_STEP: 1202,
    TOWER_BOTTLENECK_WEST_STEP: 1302,
    TOWER_BOTTLENECK_LOCATIONS: "TBL",
    ROAD_BUILD_RESET_DATA_STEP: 100000,
    ROAD_BUILD_STEP: 500,
    ROAD_BUILD_CALC_STEP: 100,
    X_ROOM_EDGE: 49,
    Y_ROOM_EDGE: 49
})